Cryptomari0 binance 5
opencrypto-io/data pull request #65
Opened 2018-11-27 16:14 UTC by cryptomari0

2018-12-09 20:01 UTC, coinmandeer-zz requested changes

2018-12-10 08:14 UTC, cryptomari0 commented on db/projects/neblio/project.yaml
> +  - title: 'neblio: Next Generation Enterprise Blockchain Solutions'
- title: 'Neblio: Next Generation Enterprise Blockchain Solutions'

2018-12-10 08:21 UTC, cryptomari0 commented on db/projects/neblio/project.yaml
> +  - title: 'neblio: Next Generation Enterprise Blockchain Solutions'
description: 'A secure, distributed, platform built for enterprise applications and services. Running on the Neblio blockchain network.'

2018-12-10 08:21 UTC, cryptomari0 commented on db/projects/neblio/project.yaml
> +  - title: 'neblio: Next Generation Enterprise Blockchain Solutions'
tags:
  - business
  - enterprise
  - blockchain

2018-12-10 08:23 UTC, cryptomari0 commented on db/projects/nuls/project.yaml
> +assets:
token_standard: ERC-20

2018-12-10 08:29 UTC, cryptomari0 commented on db/projects/ost/project.yaml
> +  location:hq: 'Berlin, Germany'
linkedin/company: ostdotcom

2018-12-10 08:30 UTC, cryptomari0 commented on db/projects/ost/project.yaml
> +  location:hq: 'Berlin, Germany'
location:hq: 'Hong Kong'

2018-12-10 08:35 UTC, cryptomari0 commented on db/projects/ost/project.yaml
> +name: OST
done

2018-12-10 08:36 UTC, cryptomari0 commented on db/projects/red-pulse-phoenix/project.yaml
> +  location:hq: 'Rooms 05 -15, 13A/F, South Tower, World Finance Centre, Harbour City, 17 Canton Road, Tsim Sha Tsui, Kowloon, Hong Kong'
location:hq: 'Kowloon, Hong Kong'
  location:node: 'Shanghai, China'

I do not know, in other hand, if there would be full addresses, we could have in the future also maps...

2018-12-10 08:37 UTC, cryptomari0 commented on db/projects/request-network/project.yaml
> +  - ivoice
- invoice

2018-12-10 09:21 UTC, cryptomari0 commented on db/projects/request-network/project.yaml
> +  - title: 'Whitepaper: Request Network: The future of commerce: A decentralized network for payment requests'
- title: 'Request Network: The future of commerce: A decentralized network for payment requests'

2018-12-10 09:34 UTC, cryptomari0 commented on db/projects/salt/project.yaml
> +name: SALT
done

2018-12-10 09:55 UTC, cryptomari0 commented on db/projects/singulardtv/project.yaml
> +name: SingularDTV
done

2018-12-14 13:10 UTC, coinmandeer commented on db/projects/request-network/project.yaml
> +  - title: 'Whitepaper: Request Network: The future of commerce: A decentralized network for payment requests'
dvojita dvoutecka? :) To zni zajimave .. je to sice kravina, ale nebylo by lepsi tam mit "Request Network: Decentralized Network for Payment Request" ?

2018-12-14 13:36 UTC, cryptomari0 commented on db/projects/polymath/project.yaml
> +name: Polymath
asset-poly-logo-square.png

2018-12-14 13:40 UTC, cryptomari0 commented on db/projects/populous/project.yaml
> +name: Populous
asset-poly-logo-full.png

2018-12-14 13:42 UTC, cryptomari0 commented on db/projects/populous/project.yaml
> +name: Populous
Actually asset-ppt-logo-full.png

2018-12-14 13:43 UTC, cryptomari0 commented on db/projects/ravencoin/project.yaml
> +name: Ravencoin
asset-rvn-logo-full

2018-12-14 13:45 UTC, cryptomari0 commented on db/projects/ravencoin/project.yaml
> +  - westeros
tags:
  - transfer
  - opensource

2018-12-14 13:49 UTC, coinmandeer-zz submitted a review, later dismissed

2018-12-14 13:49 UTC, cryptomari0 commented on db/projects/red-pulse-phoenix/project.yaml
> +name: Red Pulse Phoenix
asset-phx-logo-full.svg
asset-phx-logo-square.png

2018-12-14 13:50 UTC, cryptomari0 commented on db/projects/request-network/project.yaml
> +  - title: 'Whitepaper: Request Network: The future of commerce: A decentralized network for payment requests'
- title: 'Request Network: Decentralized Network for Payment Request'

2018-12-14 14:00 UTC, coinmandeer-zz approved these changes

2018-12-14 14:00 UTC, merged